package ecbratex

// Currency code constants.
const (
	AUD string = "AUD"
	BGN string = "BGN"
	BRL string = "BRL"
	CAD string = "CAD"
	CHF string = "CHF"
	CNY string = "CNY"
	CYP string = "CYP"
	CZK string = "CZK"
	DKK string = "DKK"
	EEK string = "EEK"
	GBP string = "GBP"
	HKD string = "HKD"
	HRK string = "HRK"
	HUF string = "HUF"
	IDR string = "IDR"
	ILS string = "ILS"
	INR string = "INR"
	ISK string = "ISK"
	JPY string = "JPY"
	KRW string = "KRW"
	LTL string = "LTL"
	LVL string = "LVL"
	MTL string = "MTL"
	MXN string = "MXN"
	MYR string = "MYR"
	NOK string = "NOK"
	NZD string = "NZD"
	PHP string = "PHP"
	PLN string = "PLN"
	ROL string = "ROL"
	RON string = "RON"
	RUB string = "RUB"
	SEK string = "SEK"
	SGD string = "SGD"
	SIT string = "SIT"
	SKK string = "SKK"
	THB string = "THB"
	TRL string = "TRL"
	TRY string = "TRY"
	USD string = "USD"
	ZAR string = "ZAR"
)
